# Generated by Django 5.2.1 on 2025-05-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empty_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_volume', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
