# Generated by Django 5.2.1 on 2025-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bottle_delete_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'verbose_name': 'Бутылка', 'verbose_name_plural': 'Бутылки'},
        ),
        migrations.AlterField(
            model_name='bottle',
            name='empty_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес пустой бутылки в граммах'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='full_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём бутылки в миллилитрах'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='full_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес полной бутылки в граммах'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название алкоголя'),
        ),
    ]
