# Generated by Django 5.2.1 on 2025-05-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bottle_options_alter_bottle_empty_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='liquid_density',
            field=models.DecimalField(decimal_places=3, default=0.789, max_digits=10, verbose_name='Плотность жидкости (г/мл)'),
        ),
    ]
